name: gochatcli
version: 0.0.1
summary: A command line chat app with a serverless backend
description: A command line chat app with a serverless backend
confinement: strict
grade: stable

apps:
  gochat:
    command: python2 goChat.py
    plugs: [home, network, network-bind]

parts:
  gochat:
    plugin: python
    source: .
    requirements: requirements.txt
    python-version: "python2"
