name: gochat
version: 0.0.1
summary: A command line chat app with a serverless backend
description: A command line chat app with a serverless backend
confinement: strict
grade: stable

apps:
  gochat:
    command: gochat
    plugs: [home, network, network-bind]

parts:
  gochat:
    plugin: python
    source: src
    python-version: "python2"
